#!/bin/bash

POLL="ls -l /dev/input/"

CUR=$($POLL)
LST=$($POLL)

finish()
{
    exit
}

trap finish SIGINT

while :; do
    if (( ${#CUR} > ${#LST} )); then
	# pause and steal active source
	$(echo "tx 14:44:46" | cec-client -s -d 1) 
	$(echo "as" | cec-client -s -d 1) 
    fi
    LST=$CUR
    CUR=$($POLL)
    sleep 1
done
